version: "3.8"
services:
  news-aggregator:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_NEWS_API_KEY=${REACT_APP_NEWS_API_KEY}
      - REACT_APP_GUARDIAN_API_KEY=${REACT_APP_GUARDIAN_API_KEY}
      - REACT_APP_NYTIMES_API_KEY=${REACT_APP_NYTIMES_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
